services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      CLICKHOUSE_DB: otel
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml", "--feature-gates=clickhouse.json"]
    volumes:
      - ./otelcol/config.yaml:/etc/otel-collector-config.yaml:ro
      - ../boulder/test/log:/data
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "5514:5514/udp" # Syslog receiver
    depends_on:
      - clickhouse
    restart: unless-stopped
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_very_bad_password
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - clickhouse
    restart: unless-stopped
    networks:
      - otel-network

volumes:
  clickhouse_data:
  grafana_data:

networks:
  otel-network:
    driver: bridge
