apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: otel
      port: 9000
      server: clickhouse
      username: grafana_reader
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
    secureJsonData:
      password: grafana_reader_very_bad_password
    isDefault: true
    editable: true
