receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  syslog:
    udp:
      listen_address: "0.0.0.0:5514"
    protocol: rfc3164

processors:
  batch:

exporters:
  clickhouse:
    endpoint: http://clickhouse:8123
    database: otel
    username: otel_writer
    password: otel_writer_very_bad_password
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, prometheus]
    logs:
      receivers: [otlp, syslog]
      processors: [batch]
      exporters: [clickhouse]

  extensions: []
