receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  syslog:
    udp:
      listen_address: "0.0.0.0:5514"
    protocol: rfc5424
  filelog:
    include:
      - /data/*.log
    exclude:
      - /data/kern.log
      - /data/rsyslogd.log
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\S+) (?P<hostname>\S+) datacenter (?P<syslogseverity>\d+) (?P<service>[^\[]+)\[(?P<pid>\d+)\]: (?P<checksum>\S+) (?P<msg>.*?)(?:JSON=(?P<json>\{.*\}))?$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'
      - type: json_parser
        parse_from: attributes.json
        parse_to: attributes.json
        if: 'attributes.json != nil'

processors:
  batch:

exporters:
  clickhouse:
    endpoint: http://clickhouse:8123
    database: otel
    username: otel_writer
    password: otel_writer_very_bad_password
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, prometheus]
    logs:
      receivers: [otlp, syslog, filelog]
      processors: [batch]
      exporters: [clickhouse]

  extensions: []
