receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  syslog:
    udp:
      listen_address: "0.0.0.0:5514"
    protocol: rfc5424
  filelog:
    include:
      - /data/*.log
    exclude:
      - /data/kern.log
      - /data/rsyslogd.log
    start_at: beginning # in the poc-poc, I want to re-parse as I reload
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\S+) (?P<hostname>\S+) (?P<datacenter>\S+) (?P<syslogseverity>\d+) (?P<service>[^\[]+)\[(?P<pid>\d+)\]: (?P<checksum>\S+) (?P<msg>.*?)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%f%j'
        severity:
          parse_from: attributes.syslogseverity
          preset: none
          overwrite_text: true
          mapping: # These values match the mapping in the collector's syslog receiver
            fatal:  0 # syslog: emerg
            error3: 1 # syslog: alert
            error2: 2 # syslog: crit
            error:  3 # syslog: err
            warn:   4 # syslog: warning
            info2:  5 # syslog: notice
            info:   6 # syslog: info
            debug:  7 # syslog: debug
      - type: move
        from: attributes.msg
        to: body

processors:
  batch:

exporters:
  clickhouse:
    endpoint: http://clickhouse:8123
    database: otel
    username: otel_writer
    password: otel_writer_very_bad_password
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, prometheus]
    logs:
      receivers: [otlp, syslog, filelog]
      processors: [batch]
      exporters: [clickhouse]

  extensions: []
